version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "listshuffler-be"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1kv3h1oegprm"
s3_prefix = "listshuffler-be"
region = "eu-central-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
