AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  listshuffler-be

  Backend for Listshuffler App

Parameters:
  RDSEndpoint:
    Type: String
  RDSUser:
    Type: String
  RDSPassword:
    Type: String
  EnvType:
    Type: String
    Default: local
    AllowedValues:
      - prod
      - test
      - local

Condition:
  isProd: !Equals [ !Ref EnvType, prod]
  isTest: !Equals [ !Ref EnvType, test]

Globals:
  Function:
    Timeout: 3
    Runtime: python3.9
    Architectures:
      - x86_64
    VpcConfig:
      SubnetIds:
        - subnet-071f89317eae740ab
        - subnet-00bed6b534c1c9117
        - subnet-09f8776cc80b883d1
      SecurityGroupIds:
        - sg-0eb0c6c1869cfa2ea
    Environment:
      Variables:
        LS_RDS_ENDPOINT: !Ref RDSEndpoint
        LS_RDS_USER: !Ref RDSUser
        LS_RDS_PWD: !Ref RDSPassword
        LS_PAGE_ORIGIN: !If [ isProd, "'http://listshuffler-fe-prod.s3-website.eu-central-1.amazonaws.com'", !If [ isTest, "'http://listshuffler-fe-test.s3-website.eu-central-1.amazonaws.com'", "'http://localhost:3000'" ]]

Resources:
  ListshufflerApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowMethods: "'GET, PUT, POST, DELETE, OPTIONS'"
        AllowOrigin: !If [ isProd, "'http://listshuffler-fe-prod.s3-website.eu-central-1.amazonaws.com'", !If [ isTest, "'http://listshuffler-fe-test.s3-website.eu-central-1.amazonaws.com'", "'http://localhost:3000'" ]]
        AllowHeaders: "'Content-type, x-api-key'"
      Auth:
        ApiKeyRequired: false
  CreateInstanceFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src
      Handler: create_instance.app.handler
      Role: arn:aws:iam::392215370007:role/lambda-vpc-role
      Events:
        CreateInstance:
          Type: Api
          Properties:
            RestApiId: !Ref ListshufflerApi
            Path: /create-instance
            Method: post
  ClearInstancesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src
      Handler: clear_instances.app.handler
      Role: arn:aws:iam::392215370007:role/lambda-vpc-role
      Events:
        ScheduledEvent:
          Type: Schedule
          Properties:
            Schedule: rate(1 day)
            Enabled: True
