AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  listshuffler-be

  Backend for Listshuffler App

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Parameters:
  RDSEndpoint:
    Type: String
  RDSUser:
    Type: String
  RDSPassword:
    Type: String

Resources:
  CreateInstanceFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: create_instance
      Handler: app.handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Role: arn:aws:iam::392215370007:role/lambda-vpc-role
      VpcConfig:
        SubnetIds:
          - subnet-071f89317eae740ab
          - subnet-00bed6b534c1c9117
          - subnet-09f8776cc80b883d1
        SecurityGroupIds:
          - sg-0eb0c6c1869cfa2ea
      Environment:
        Variables:
          RDS_ENDPOINT: !Ref RDSEndpoint
          RDS_USER: !Ref RDSUser
          RDS_PWD: !Ref RDSPassword
      Events:
        CreateInstance:
          Type: Api
          Properties:
            Path: /create-instance
            Method: post
