version = 0.1
[default]
[default.pipeline_bootstrap]
[default.pipeline_bootstrap.parameters]
pipeline_user = "arn:aws:iam::392215370007:user/aws-sam-cli-managed-test-pipeline-res-PipelineUser-T0IJMHTHS0UM"

[test]
[test.pipeline_bootstrap]
[test.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::392215370007:role/aws-sam-cli-managed-test-pip-PipelineExecutionRole-JXP92MR1N1EK"
cloudformation_execution_role = "arn:aws:iam::392215370007:role/aws-sam-cli-managed-test-CloudFormationExecutionR-M75E1UPEFY5Y"
artifacts_bucket = "aws-sam-cli-managed-test-pipeline-artifactsbucket-i5tsrcxwd9mb"
image_repository = ""
region = "eu-central-1"

[prod]
[prod.pipeline_bootstrap]
[prod.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::392215370007:role/aws-sam-cli-managed-prod-pip-PipelineExecutionRole-1M9MCCWFZUOBM"
cloudformation_execution_role = "arn:aws:iam::392215370007:role/aws-sam-cli-managed-prod-CloudFormationExecutionR-XN7N2RTHS8YN"
artifacts_bucket = "aws-sam-cli-managed-prod-pipeline-artifactsbucket-nbm8ekja0jja"
image_repository = ""
region = "eu-central-1"
