name: CI/CD pipeline

on:
  push:
    branches:
      - 'main'
      - 'test'
  pull_request:
    branches:
      - 'main'
      - 'test'

env:
  USER_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  USER_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  FE-DIR: listshuffler-fe
  BE-DIR: listshuffler-be
  TESTING_STACK_NAME: listshuffler-test-be
  TESTING_ARTIFACTS_BUCKET: aws-sam-cli-managed-test-pipeline-artifactsbucket-i5tsrcxwd9mb
  TESTING_REGION: eu-central-1
  TESTING_FE_BUCKET: listshuffler-fe-test
  PROD_STACK_NAME: listshuffler-prod-be
  PROD_ARTIFACTS_BUCKET: aws-sam-cli-managed-prod-pipeline-artifactsbucket-nbm8ekja0jja
  PROD_REGION: eu-central-1
  PROD_FE_BUCKET: listshuffler-fe-prod

jobs:
  test-fe:
    if: github.ref == 'refs/heads/test'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        working-directory: ${{ env.FE-DIR }}
        run: npm ci
      #- name: Test functionality
      #  working-directory: ${{ env.FE-DIR }}
      #  run: npm run test
      - name: Make sure build compiles properly
        working-directory: ${{ env.FE-DIR }}
        run: npm run build:test

  test-be:
    if: github.ref == 'refs/heads/test'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Installing dependencies
        working-directory: ${{ env.BE-DIR }}
        run: |
          pip install -U pip
          pip install -r tests/requirements.txt
      #- name: Test functionality
      #  working-directory: ${{ env.BE-DIR }}
      #  run: python -m pytest tests/unit -v

  build-and-deploy-test:
    needs: [test-fe, test-be]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: aws-actions/setup-sam@v1

      - name: Install packages
        working-directory: ${{ env.FE-DIR }}
        run: npm ci
      - name: Build app
        working-directory: ${{ env.FE-DIR }}
        run: npm run build:test

      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ env.TESTING_FE_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ env.USER_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ env.USER_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ env.TESTING_REGION }}
          SOURCE_DIR: ${{ env.FE-DIR }}/build

      - run: sam build --template ${{ env.BE-DIR }}/template.yaml --use-container

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ env.USER_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.USER_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.TESTING_REGION }}

      - name: Deploy to test stack
        shell: bash
        run: |
          sam deploy --stack-name ${TESTING_STACK_NAME} \
            --capabilities CAPABILITY_IAM \
            --s3-bucket ${TESTING_ARTIFACTS_BUCKET} \
            --region ${TESTING_REGION} \
            --no-fail-on-empty-changeset \
            --parameter-overrides \
            RDSEndpoint=${{ secrets.T_RDS_ENDPOINT }} \
            RDSUser=${{ secrets.T_RDS_USER }} \
            RDSPassword=${{ secrets.T_RDS_PWD }} \
            PageOrigin=test

  build-and-deploy-prod:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: aws-actions/setup-sam@v1

      - name: Install packages
        working-directory: ${{ env.FE-DIR }}
        run: npm ci
      - name: Build app
        working-directory: ${{ env.FE-DIR }}
        run: npm run build:prod

      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ env.PROD_FE_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ env.USER_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ env.USER_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ env.PROD_REGION }}
          SOURCE_DIR: ${{ env.FE-DIR }}/build

      - run: sam build --template ${{ env.BE-DIR }}}/template.yaml --use-container

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ env.USER_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.USER_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.TESTING_REGION }}
      
      - name: Deploy to prod stack
        shell: bash
        run: |
          sam deploy --stack-name ${PROD_STACK_NAME} \
            --capabilities CAPABILITY_IAM \
            --s3-bucket ${PROD_ARTIFACTS_BUCKET} \
            --region ${PROD_REGION} \
            --no-fail-on-empty-changeset \
            --parameter-overrides \
            RDSEndpoint=${{ secrets.P_RDS_ENDPOINT }} \
            RDSUser=${{ secrets.P_RDS_USER }} \
            RDSPassword=${{ secrets.P_RDS_PWD }} \
            PageOrigin=prod
